version: '3.8'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: abrvia
      MONGO_INITDB_USERNAME: via
      MONGO_INITDB_PASSWORD: 123456
    ports: 
      - 27017:27017
    volumes:
      - ./database/dbdata:/data/db
      - ./database/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh